name: build

# on:
#   push:
#     branches:
#       - main
#     tags:
#       - '*'
on:
  push:
    tags:
      - "v*.*.*"
env:
  FLUTTER_VERSION: "3.29.0"

permissions:
  contents: write

jobs:
  
  # build-android:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Clone repository
  #       uses: actions/checkout@v4
  #     - name: Set up Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version: ${{ env.FLUTTER_VERSION }}
  #         channel: stable

  #     - name: Build
  #       run: |
  #         flutter pub get
  #         flutter test
  #         flutter build apk
  #     - name: Release
  #       uses: softprops/action-gh-release@v2
  #       # if: startsWith(github.ref, 'refs/tags/')
  #       with:
  #         files: build/app/outputs/flutter-apk/app-release.apk   
  #     - name: Upload
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: release-apk
  #         # Try running the build locally with the build command to be sure of this path
  #         path: build/app/outputs/flutter-apk/app-release.apk 

  # build-ios:
  #   runs-on: macos-latest
  #   steps:
  #     - name: Clone repository
  #       uses: actions/checkout@v4
  #     - name: Set up Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version: ${{ env.FLUTTER_VERSION }}
  #         channel: stable
  #     # - run: flutter pub get
  #     # - run: flutter test
  #     # - run: flutter build ios --release --no-codesign
  #     - name: Build
  #       run: |
  #         flutter pub get
  #         flutter test
  #         flutter build ios --release --no-codesign
  #         mkdir Payload
  #         mkdir dist
  #         cp -r build/ios/iphoneos/Runner.app Payload
  #         zip -r -y Payload.zip Payload/Runner.app
  #         mv Payload.zip dist/app-ios.ipa
  #     - name: Release
  #       uses: softprops/action-gh-release@v2
  #       # if: startsWith(github.ref, 'refs/tags/')
  #       with:
  #         files: dist/app-ios.ipa
  #     - name: Upload
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: release-ipa
  #         # Try running the build locally with the build command to be sure of this path
  #         path: dist/app-ios.ipa  

  # build-web:
  #   runs-on: ubuntu-latest
  #   steps:
  #       - name: Clone repository
  #         uses: actions/checkout@v4
  #       - name: Set up Flutter
  #         uses: subosito/flutter-action@v2
  #         with:
  #           flutter-version: ${{ env.FLUTTER_VERSION }}
  #           channel: stable
  #       - name: Build
  #         run: |
  #           flutter pub get
  #           flutter test
  #           flutter build web
  #           zip -r -y web.zip build/web
  #       - name: Release
  #         uses: softprops/action-gh-release@v2
  #         # if: startsWith(github.ref, 'refs/tags/')
  #         with:
  #           files: web.zip
  #       - name: Upload
  #         uses: actions/upload-artifact@v4
  #         with:
  #           name: release-web
  #           # Try running the build locally with the build command to be sure of this path
  #           path: web.zip 



  build-windows:
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable

      - name: Build
        run: |
          flutter pub get
          flutter test
          dart run fastforge:main release  --name prod
          Copy-Item -Path 'dist/*/*.exe' -Destination 'dist/app-win.exe'
          
      - name: Release
        uses: softprops/action-gh-release@v2
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/app-win.exe   
      # - name: Upload
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: release-apk
      #     # Try running the build locally with the build command to be sure of this path
      #     path: dist/app-win.exe 

  